### ISSUE TITLE
Satellite Uplink not working

### ISSUE THREAD

**Issue by qmsm** [mtgred/netrunner#249]
I think that's about it. When I click it nothing happens. Card Status list says it should work.

**Comment by JoelCFC25** [comment]
It definitely appears to be wrong--the code includes `:req (req tagged)`, but there is no such requirement to play the event.

**Comment by mtgred** [comment]
Thanks for reporting the issue. It's indeed not working because of the tagged requirement.

It has been fixed.

**Comment by qmsm** [comment]
I'm afraid still not working for me, unless I have some sort of caching issue (if that's possible)?

**Comment by mtgred** [comment]
I forgot to add the fix to the last update. The fix will be deployed in the next update this afternoon.
