### ISSUE TITLE
Cutlery Events Broken, Divide & Conquer + Black Hat HQ Access

### ISSUE THREAD

**Issue by whiterabbit1670** [mtgred/netrunner#3798]
All 3 events; Knifed, Forked, and Spooned cause the game to lock up before the server to be run is chosen. This can only be fixed by /undo-turn, making the events useless.

When combining Black Hat + Divide & Conquer, the Archives and R&D accesses work fine, but all of HQ is accessed, regardless of the number of cards in HQ.

**Comment by jwarwick** [comment]
Cutlery crash if fixed in #3794

**Comment by whiterabbit1670** [comment]
Cutlery still not allowing choice of server to run. Prompt opens, but no choice can be made.

**Comment by NoahTheDuke** [comment]
I'd love to see that log. I can't reproduce this.
