### ISSUE TITLE
"Illegal" Decks Change to Legal on Selection

### ISSUE THREAD

**Issue by analyzechris** [mtgred/netrunner#5066]
In Deck Builder, many decks are erroneously marked as _Illegal_ (be it Standard, Snapshot Plus, Eternal, or Casual) but change their legality tag to legal once you select them. Attached is an example of a Tenin deck that showed up as _Standard Illegal_ until I clicked on it, at which point it changed to _Standard Legal_ and an AgInfusion deck that remained _Standard Illegal_ upon selection.

**Mac OS X 10.15.2**
- Chrome – 81.0.4044.129
- FireFox – 71.0
- Safari – 13.0.4

<img width="438" alt="Screen Shot 2020-04-30 at 5 08 39 PM" src="https://user-images.githubusercontent.com/64614578/80759854-f7665e80-8b05-11ea-96b9-18cda0a6e28a.png">

<img width="432" alt="Screen Shot 2020-04-30 at 5 15 08 PM" src="https://user-images.githubusercontent.com/64614578/80760010-372d4600-8b06-11ea-8b95-0bd5256a69ab.png">

**Comment by qwitwa** [comment]
I'm bumping this with more screenshots since there's been a few recent issues about deck legality like #5311 and #5181 (I notice #4242 though closed seems relevant). This is what I (a new user) see when going into the deckbuilder interface:

![Uploading Screen Shot 2020-11-14 at 06.23.57.png…]()
When clicking the decks in the left hand pane:
<img width="1673" alt="Screen Shot 2020-11-14 at 06 24 14" src="https://user-images.githubusercontent.com/2302478/99141493-c386fc80-2643-11eb-84bc-6ff7d45779be.png">
<img width="1678" alt="Screen Shot 2020-11-14 at 06 24 26" src="https://user-images.githubusercontent.com/2302478/99141494-c550c000-2643-11eb-893a-c8b3ca117f94.png">

The decks show up as illegal when selected in the lobby.

**Comment by NoahTheDuke** [comment]
This is a known issue. When we update the server with new ban lists, we don't re-validate all existing decks, so we trust the stores deck info when loading the decks. Once you click on the deck, it is recalculated. I wrote a script to update all decks but it's been crashing when I try it so it's not live yet. Hopefully I can get that fixed up soon.

**Comment by jwarwick** [comment]
Fixed in #5394

**Comment by qwitwa** [comment]
Behaviour still appears to be occurring on live site despite this being in prod now: 

Before clicks:
<img width="472" alt="Screen Shot 2020-11-26 at 04 54 39" src="https://user-images.githubusercontent.com/2302478/100309994-177ad500-2fa4-11eb-95ad-bfd03dbec89d.png">

After clicks:
<img width="408" alt="Screen Shot 2020-11-26 at 04 54 46" src="https://user-images.githubusercontent.com/2302478/100309998-19449880-2fa4-11eb-8452-881533455dcd.png">

**Comment by jwarwick** [comment]
#5402 Fixes the second part of this issue.
