### ISSUE TITLE
[Art] Mestnichestvo seems to have reverted to its older art in high quality card images

### ISSUE THREAD

**Issue by talha-ahsan** [mtgred/netrunner#8002]
Not sure when this happened, looks like Mestnichestvo's art reverted to the original "shield" version instead of the "tree" version that's the latest one.

**Comment by talha-ahsan** [comment]
Discussion on GLC seems to indicate it's only reproducible with high quality card images too

**Comment by NBKelly** [comment]
hmm - so from what I understand, the high quality card images were ripped from some of the nsg PnP's by an anonymous individual - so I think they probably exist in the nsg pnp's as well 👀

**Comment by NBKelly** [comment]
Is it still showing up, or did we get it?

**Comment by xiaat** [comment]
I checked back 12 hours after the issue was discovered and for me it was already fixed

**Comment by talha-ahsan** [comment]
Oddly I’m still seeing reports of this happening on GLC. I wonder if caching is an issue on the client side now?

-
________________________________

**Comment by NBKelly** [comment]
hmm - I think it most likely is browser caching. If they clear their caches (this is different from just control+f5 now, though that *might* work), it should be fixed.
